spring:
  application:
    name: price-agregator
server:
  port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8001/eureka}
  instance:
    preferIpAddress: true