version: '2.1'

services:
  service-discovery:
    restart: always
    build: service-discovery
    ports:
      - 8001:8001


  service-config:
    restart: always
    build: service-config
    ports:
      - 8010:8010

  product-catalogue:
    restart: always
    build: product-catalogue
    ports:
      - 8002:8002
    depends_on:
      - service-discovery
      - service-config
    environment:
      SPRING_PROFILES_ACTIVE: prod

  price-agregator:
    restart: always
    build: price-agregator
    ports:
      - 8003:8003
    depends_on:
      - service-discovery
      - service-config
    environment:
      SPRING_PROFILES_ACTIVE: prod

  price-comparator-front:
    restart: always
    build: price-comparator-front
    ports:
      - 8005:8005
    depends_on:
      - service-discovery
      - service-config
      - price-agregator
      - product-catalogue
    environment:
      SPRING_PROFILES_ACTIVE: prod