server:
  port: 8011
  context-path: /api

spring:
  aop:
    proxyTargetClass: true

---
spring:
  profiles: default

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8001/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    products:
      url: http://localhost:8002/api/products
    prices:
      url: http://localhost:8003/api/prices
---

spring:
  profiles: prod

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-discovery:8001/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    products:
      url: http://product-catalogue:8002/api/products
    prices:
      url: http://price-agregator:8003/api/prices