server:
  port: 8005

---
spring:
  profiles: default

productCatalogueUri: http://localhost:8011/products
priceServiceUri: http://localhost:8011/prices

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8001/eureka}
  instance:
    preferIpAddress: true


---
spring:
  profiles: prod

productCatalogueUri: http://api-gateway:8011/products
priceServiceUri: http://api-gateway:8011/prices

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-discovery:8001/eureka}
  instance:
    preferIpAddress: true