spring:
  application:
    name: product-catalogue
server:
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8001/eureka}
  instance:
    preferIpAddress: true