productCatalogueUri: http://localhost:8002/api
priceServiceUri: http://localhost:8003/api

spring:
  application:
    name: price-comparator-front
server:
  port: 8004
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8001/eureka}
  instance:
    preferIpAddress: true