productCatalogueUri: http://product-catalogue:8002/api
priceServiceUri: http://price-agregator:8003/api

spring:
  application:
    name: price-comparator-front
server:
  port: 8005

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-discovery:8001/eureka}
  instance:
    preferIpAddress: true